Repository OriginTrail/dkg-evm-module, pull requests merged in 2022-12, with the labels that each got.

#42 Staking integration
  contracts/Profile.sol
  contracts/Staking.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/ShardingTableStorage.sol
Labels: enhancement

#43 Added rewards to ProfileStorage for operator fees collection
  contracts/Profile.sol
  contracts/ServiceAgreementV1.sol
  contracts/Staking.sol
  contracts/storage/ProfileStorage.sol
Labels: enhancement

#41 Reworked contracts (except ServiceAgreement) + gas cost optimizations + Staking
  contracts/Assertion.sol
  contracts/AssertionRegistry.sol
  contracts/ERC20Token.sol
  contracts/HashingProxy.sol
  contracts/Hub.sol
  contracts/Identity.sol
  contracts/Profile.sol
  contracts/ScoringProxy.sol
  contracts/ServiceAgreement.sol
  contracts/ServiceAgreementV1.sol
  contracts/ShardingTable.sol
  contracts/Shares.sol
  contracts/Staking.sol
  contracts/assets/AbstractAsset.sol
  contracts/assets/ContentAsset.sol
  contracts/constants/IdentityConstants.sol
  contracts/constants/ShardingTableConstants.sol
  contracts/hashing/sha256.sol
  contracts/interface/IERC734Extended.sol
  contracts/interface/IHashFunction.sol
  contracts/interface/IScoreFunction.sol
  contracts/interface/Indexable.sol
  contracts/interface/Named.sol
  contracts/scoring/log2pldsf.sol
  contracts/storage/AssertionStorage.sol
  contracts/storage/IdentityStorage.sol
  contracts/storage/ParametersStorage.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/ServiceAgreementStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/storage/ShardingTableStorage.sol
  contracts/storage/StakingStorage.sol
  contracts/structs/AssertionStructs.sol
  contracts/structs/ServiceAgreementStructsV1.sol
  contracts/structs/ShardingTableStructs.sol
  contracts/utils/ByteArr.sol
  contracts/utils/UnorderedIndexableContractDynamicSet.sol
  contracts/utils/UnorderedNamedContractDynamicSet.sol
  migrations/2_total_migration.js
  test/staking.test.js
  truffle-config.js
Labels: enhancement

#44 V6/updated contracts test
  build/contracts/AbstractAsset.json
  build/contracts/Assertion.json
  build/contracts/AssertionStorage.json
  build/contracts/AssertionStructs.json
  build/contracts/ContentAsset.json
  build/contracts/ERC20Token.json
  build/contracts/HashingProxy.json
  build/contracts/Hub.json
  build/contracts/IERC734Extended.json
  build/contracts/IHashFunction.json
  build/contracts/IScoreFunction.json
  build/contracts/Identity.json
  build/contracts/IdentityStorage.json
  build/contracts/Indexable.json
  build/contracts/Log2PLDSF.json
  build/contracts/Named.json
  build/contracts/ParametersStorage.json
  build/contracts/Profile.json
  build/contracts/ProfileStorage.json
  build/contracts/SHA256.json
  build/contracts/ScoringProxy.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementStructsV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/ShardingTableStructs.json
  build/contracts/Shares.json
  build/contracts/Staking.json
  build/contracts/StakingStorage.json
  build/contracts/UnorderedIndexableContractDynamicSetLib.json
  build/contracts/UnorderedNamedContractDynamicSetLib.json
  contracts/Assertion.sol
  contracts/Identity.sol
  contracts/Profile.sol
  contracts/ServiceAgreementV1.sol
  contracts/ShardingTable.sol
  contracts/Staking.sol
  contracts/assets/ContentAsset.sol
  contracts/storage/AssertionStorage.sol
  contracts/storage/IdentityStorage.sol
  contracts/storage/ParametersStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/storage/ShardingTableStorage.sol
  migrations/2_total_migration.js
Labels: enhancement

#47 Naming fixes (ServiceAgreementV1)
  build/contracts/AbstractAsset.json
  build/contracts/Assertion.json
  build/contracts/AssertionStorage.json
  build/contracts/AssertionStructs.json
  build/contracts/ContentAsset.json
  build/contracts/ERC20Token.json
  build/contracts/HashingProxy.json
  build/contracts/Hub.json
  build/contracts/IERC734Extended.json
  build/contracts/IHashFunction.json
  build/contracts/IScoreFunction.json
  build/contracts/Identity.json
  build/contracts/IdentityStorage.json
  build/contracts/Indexable.json
  build/contracts/Log2PLDSF.json
  build/contracts/Named.json
  build/contracts/ParametersStorage.json
  build/contracts/Profile.json
  build/contracts/ProfileStorage.json
  build/contracts/SHA256.json
  build/contracts/ScoringProxy.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementStructsV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/ShardingTableStructs.json
  build/contracts/Shares.json
  build/contracts/Staking.json
  build/contracts/StakingStorage.json
  build/contracts/UnorderedIndexableContractDynamicSetLib.json
  build/contracts/UnorderedNamedContractDynamicSetLib.json
  contracts/ServiceAgreementV1.sol
  contracts/Staking.sol
  contracts/assets/ContentAsset.sol
  package-lock.json
  package.json
Labels: enhancement

#48 Changed duplicate commit submission check
  build/contracts/ContentAsset.json
  build/contracts/Identity.json
  build/contracts/Profile.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/Staking.json
  contracts/ServiceAgreementV1.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  package-lock.json
  package.json
Labels: enhancement

#49 V6/insert commit fix
  build/contracts/ContentAsset.json
  build/contracts/Identity.json
  build/contracts/Profile.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/Staking.json
  contracts/ServiceAgreementV1.sol
  package-lock.json
  package.json
Labels: enhancement

#50 Added identityId to the wrapper struct for ShardingTable
  build/contracts/ContentAsset.json
  build/contracts/Identity.json
  build/contracts/Profile.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/ShardingTableStructs.json
  build/contracts/Staking.json
  contracts/ShardingTable.sol
  contracts/structs/ShardingTableStructs.sol
  package-lock.json
  package.json
Labels: enhancement

#55 Small fixes after review, added withdrawals accumulation mechanism
  contracts/Profile.sol
  contracts/Staking.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/StakingStorage.sol
Labels: enhancement

#56 Added assertion issuers from AssertionStorage to ContentAsset
  contracts/Assertion.sol
  contracts/assets/ContentAsset.sol
  contracts/storage/AssertionStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/structs/AssertionStructs.sol
Labels: enhancement

#52 Delay for withdrawal functions
  contracts/Profile.sol
  contracts/Staking.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/StakingStorage.sol
Labels: enhancement

#72 Fixed hashing/scoring proxy function modifiers
  contracts/HashingProxy.sol
  contracts/ScoringProxy.sol
  contracts/ServiceAgreementV1.sol
  contracts/interface/IHashFunction.sol
  contracts/interface/IScoreFunction.sol
  contracts/scoring/log2pldsf.sol
Labels: v6, improvement

#74 Splitted ContentAsset storage, replaced Ownable by Hub owner
  contracts/Assertion.sol
  contracts/ERC20Token.sol
  contracts/HashingProxy.sol
  contracts/Hub.sol
  contracts/ScoringProxy.sol
  contracts/ServiceAgreementV1.sol
  contracts/assets/AbstractAsset.sol
  contracts/assets/ContentAsset.sol
  contracts/scoring/log2pldsf.sol
  contracts/storage/IdentityStorage.sol
  contracts/storage/ParametersStorage.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/storage/ShardingTableStorage.sol
  contracts/storage/StakingStorage.sol
  contracts/storage/WhitelistStorage.sol
  contracts/storage/assets/ContentAssetStorage.sol
  contracts/structs/assets/ContentAssetStructs.sol
  migrations/2_total_migration.js
  test/hub.test.js
Labels: v6, improvement

#70 Logger, updated addresses, requires
  contracts/Assertion.sol
  contracts/ERC20Token.sol
  contracts/HashingProxy.sol
  contracts/Hub.sol
  contracts/ScoringProxy.sol
  contracts/ServiceAgreementV1.sol
  contracts/assets/AbstractAsset.sol
  contracts/assets/ContentAsset.sol
  contracts/scoring/log2pldsf.sol
  contracts/storage/IdentityStorage.sol
  contracts/storage/ParametersStorage.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/storage/ShardingTableStorage.sol
  contracts/storage/StakingStorage.sol
  contracts/storage/WhitelistStorage.sol
  contracts/storage/assets/ContentAssetStorage.sol
  contracts/structs/assets/ContentAssetStructs.sol
  migrations/2_total_migration.js
  reports/otp_testnet_contracts.json
  test/hub.test.js
Labels: v6, improvement

#73 Main release: Tests for assertionStorage contract
  test/assertionStorage.test.js
Labels: tests

#76 Main release: tests for whitelistStorage contract
  test/whitelistStorage.test.js
Labels: tests

#77 Added missing contract init, removed junk
  .gitignore
  build/contracts/AssertionRegistry.json
  build/contracts/AssertionStructs.json
  build/contracts/ContentAssetStructs.json
  build/contracts/IERC734Extended.json
  build/contracts/IHashingFunction.json
  build/contracts/IScoringFunction.json
  build/contracts/IndexAsset.json
  build/contracts/PLDSF.json
  build/contracts/ServiceAgreementStorage.json
  build/contracts/ServiceAgreementStructsV1.json
  build/contracts/ShardingTableStructs.json
  build/contracts/Shares.json
  build/contracts/UnorderedIndexableContractDynamicSetLib.json
  build/contracts/UnorderedNamedContractDynamicSetLib.json
  contracts/Profile.sol
  contracts/ShardingTable.sol
Labels: bug, v6, improvement

#79 Commented out-of-date test, updated metadata and .gitignore
  .gitignore
  build/contracts/AbstractAsset.json
  build/contracts/Assertion.json
  build/contracts/AssertionStorage.json
  build/contracts/ContentAsset.json
  build/contracts/ContentAssetStorage.json
  build/contracts/ERC20Token.json
  build/contracts/HashingProxy.json
  build/contracts/Hub.json
  build/contracts/IHashFunction.json
  build/contracts/IScoreFunction.json
  build/contracts/Identity.json
  build/contracts/IdentityStorage.json
  build/contracts/Indexable.json
  build/contracts/Log2PLDSF.json
  build/contracts/Named.json
  build/contracts/ParametersStorage.json
  build/contracts/Profile.json
  build/contracts/ProfileStorage.json
  build/contracts/SHA256.json
  build/contracts/ScoringProxy.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/Staking.json
  build/contracts/StakingStorage.json
  build/contracts/Versioned.json
  build/contracts/WhitelistStorage.json
  test/contentAsset.test.js
Labels: chore, internal process

#80 Added custom names/symbols for shares tokens
  contracts/Profile.sol
  contracts/storage/ProfileStorage.sol
Labels: feature, v6

#84 Added guardian to protect contracts holding tokens
  build/contracts/Assertion.json
  build/contracts/ContentAsset.json
  build/contracts/Guardian.json
  build/contracts/ICustodian.json
  build/contracts/Identity.json
  build/contracts/Profile.json
  build/contracts/ProfileStorage.json
  build/contracts/ServiceAgreementStorageV1.json
  build/contracts/ServiceAgreementV1.json
  build/contracts/ShardingTable.json
  build/contracts/ShardingTableStorage.json
  build/contracts/Staking.json
  build/contracts/StakingStorage.json
  contracts/Guardian.sol
  contracts/Profile.sol
  contracts/interface/ICustodian.sol
  contracts/storage/ProfileStorage.sol
  contracts/storage/ServiceAgreementStorageV1.sol
  contracts/storage/StakingStorage.sol
  package-lock.json
  package.json
  test/profile-storage.test.js
  test/staking.test.js
Labels: feature, v6

#89 Added checks.yml github workflow for linting/tests
  .github/workflows/checks.yml
Labels: chore, internal process, improvement

#90 Added github workflows for releases npm-publish and linting/tests checks
  .github/actions/setup/action.yml
  .github/workflows/checks.yml
  .github/workflows/npm-publish.yml
Labels: chore, internal process

#86 Main release: Refactored and added tests for Profile contract
  test/profile.test.js
  test/whitelistStorage.test.js
Labels: tests

#93 Contract addresses updated for mainnet and testnet
  package.json
  reports/otp_mainnet_contracts.json
  reports/otp_testnet_contracts.json
Labels: chore

#94 Added deployed devnet contract addresses, updated env params usage
  .env.example
  README.md
  migrations/2_total_migration.js
  package.json
  reports/otp_devnet_contracts.json
  scripts/deploy.js
  scripts/whitelist.js
  truffle-config.js
Labels: chore
