Repository OriginTrail/dkg-evm-module, pull requests merged in 2023-07, with the labels that each got.

#182 fix reward calculation
  contracts/ProofManagerV1.sol
  contracts/ProofManagerV1U1.sol
  package-lock.json
  package.json
  test/unit/ProofManagerV1.test.ts
  test/unit/ProofManagerV1U1.test.ts
Labels: bug, v6

#185 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#187 Contracts deployment on otp_testnet
  deployments/otp_testnet_contracts.json
Labels: chore

#188 Contracts deployment on otp_mainnet
  deployments/otp_mainnet_contracts.json
Labels: chore

#186 encode_data task example
  README.md
Labels: documentation
