Repository OriginTrail/dkg-evm-module, pull requests merged in 2023-04, with the labels that each got.

#141 Deployment scripts fix
  deploy/001_deploy_hub.ts
  deploy/003_deploy_parameters_storage.ts
Labels: bug

#140 [FAILED] Contracts deployment on otp_alphanet
  deployments/otp_alphanet_contracts.json
Labels: chore

#143 Fixed deployment script issue
  deploy/003_deploy_parameters_storage.ts
Labels: internal process

#142 [FAILED] Contracts deployment on otp_alphanet
  deployments/otp_alphanet_contracts.json
Labels: chore

#144 Added wait for initialize mining during local deployment
  utils/helpers.ts
Labels: internal process

#145 Deployment forwardCall issue fix
  abi/HubController.json
  contracts/HubController.sol
  deploy/001_deploy_hub.ts
  deploy/003_deploy_parameters_storage.ts
  deploy/006_deploy_sha256.ts
  deploy/008_deploy_log2pldsf.ts
  deploy/029_deploy_content_asset.ts
  deploy/998_initialize_contracts.ts
  utils/helpers.ts
Labels: internal process

#146 Fixed helpers deploy function
  deploy/008_deploy_log2pldsf.ts
  deploy/029_deploy_content_asset.ts
  utils/helpers.ts
Labels: internal process

#147 Fixed HubController modifier, ParametersStorage params setting
  contracts/HubController.sol
  deploy/003_deploy_parameters_storage.ts
  deploy/998_initialize_contracts.ts
  hardhat.node.config.ts
Labels: bug

#148 Contracts deployment on otp_alphanet
  deployments/otp_alphanet_contracts.json
Labels: chore

#149 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#150 Changed the order of setting ContentAsset contracts in the Hub
  deploy/029_deploy_content_asset.ts
  tasks/low_level_call_data_encoder.ts
Labels: bug

#151 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#152 Fixed flag in the ContentAsset deployment script
  deploy/029_deploy_content_asset.ts
Labels: bug

#153 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#154 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#155 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore

#156 Old client backwards compatible without restart
  deploy/016_deploy_service_agreement_storage_proxy.ts
  deploy/019_deploy_assertion.ts
  deploy/022_deploy_staking.ts
  deploy/023_deploy_profile.ts
  deploy/024_deploy_commit_manager_v1.ts
  deploy/025_deploy_proof_manager_v1.ts
  deploy/026_deploy_commit_manager_v1_u1.ts
  deploy/027_deploy_proof_manager_v1_u1.ts
  deploy/028_deploy_service_agreement_v1.ts
  deploy/029_deploy_content_asset.ts
Labels: internal process, improvement

#157 Contracts deployment on otp_alphanet
  deployments/otp_alphanet_contracts.json
Labels: chore

#158 Removed automatic HubController deployment for testnet/mainnet
  deploy/001_deploy_hub.ts
  deployments/otp_testnet_contracts.json
Labels: internal process, improvement

#160 Changed onlyOwnerOrMultiSigOwner modifier in the HubController
  .lintstagedrc
  .prettierignore
  .solhintignore
  abi/MultiSigWallet.json
  contracts/HubController.sol
  contracts/MultiSigWallet.sol
  hardhat.node.config.ts
  index.ts
Labels: improvement

#162 Change gas limit on alphanet deployment
  hardhat.config.ts
Labels: chore

#163 Contracts deployment on otp_alphanet
  deployments/otp_alphanet_contracts.json
Labels: chore

#164 Set up testnet hub controller address
  deploy/001_deploy_hub.ts
  deployments/otp_testnet_contracts.json
Labels: chore

#165 Contracts deployment on otp_testnet
  deployments/otp_testnet_contracts.json
Labels: chore

#167 Commented out HubController tx in the deployment script, moved logs b…
  deploy/998_initialize_contracts.ts
  deployments/otp_alphanet_contracts.json
Labels: bug

#168 Contracts deployment on otp_mainnet
  deployments/otp_mainnet_contracts.json
Labels: chore

#169 Cleaned junk needed only for 6.0.4 release
  deploy/016_deploy_service_agreement_storage_proxy.ts
  deploy/019_deploy_assertion.ts
  deploy/028_deploy_service_agreement_v1.ts
  deploy/029_deploy_content_asset.ts
  deploy/998_initialize_contracts.ts
Labels: internal process

#170 Fixed ServiceAgreementV1U1 object creation bug
  contracts/assets/ContentAsset.sol
Labels: bug

#171 Contracts deployment on otp_mainnet
  deployments/otp_mainnet_contracts.json
Labels: chore

#173 Contracts deployment on otp_testnet
  deployments/otp_testnet_contracts.json
Labels: chore

#174 Contracts deployment on otp_devnet
  deployments/otp_devnet_contracts.json
Labels: chore
