Repository OriginTrail/dkg-evm-module, pull requests merged in 2023-01, with the labels that each got.

#97 ABI Format Update
  abi/AbstractAsset.json
  abi/Assertion.json
  abi/AssertionStorage.json
  abi/ContentAsset.json
  abi/ContentAssetStorage.json
  abi/ERC20Token.json
  abi/Guardian.json
  abi/HashingProxy.json
  abi/Hub.json
  abi/ICustodian.json
  abi/IHashFunction.json
  abi/IScoreFunction.json
  abi/Identity.json
  abi/IdentityStorage.json
  abi/Indexable.json
  abi/Named.json
  abi/ParametersStorage.json
  abi/Profile.json
  abi/ProfileStorage.json
  abi/ScoringProxy.json
  abi/ServiceAgreementStorageV1.json
  abi/ServiceAgreementV1.json
  abi/ShardingTable.json
  abi/ShardingTableStorage.json
  abi/Staking.json
  abi/StakingStorage.json
  abi/Versioned.json
  abi/WhitelistStorage.json
  hardhat.config.ts
Labels: v6, improvement

#98 Reworked tests for AssertionStorage & ParametersStorage contracts using Hardhat
  test/assertionStorage.test.ts
  test/parametersStorage.test.ts
  test/whitelistStorage.test.ts
Labels: tests

#99 Reworked tests for ProfileStorage contract using Hardhat
  test/profileStorage.test.ts
Labels: tests

#100 Identity & IdentityStorage contracts tests using Hardhat
  test/identity.test.ts
  test/identityStorage.test.ts
Labels: tests

#102 Tests for ShardingTableStorage contract using Hardhat
  test/shardingTableStorage.test.ts
Labels: tests, awaiting review

#104 Bugfixes for deployment on parachains
  .env.example
  README.md
  deploy/002_deploy_token.ts
  deploy/006_deploy_sha256.ts
  deploy/008_deploy_log2pldsf.ts
  deploy/009_deploy_assertion_storage.ts
  deploy/012_deploy_staking_storage.ts
  deploy/013_deploy_profile_storage.ts
  deploy/014_deploy_service_agreement_storage_v1.ts
  deployments/otp_alphanet_contracts.json
  deployments/otp_devnet_contracts.json
  deployments/otp_mainnet_contracts.json
  deployments/otp_testnet_contracts.json
  hardhat.config.ts
  package.json
  utils/helpers.ts
Labels: v6, internal process

#103 Tests reimplementation for Hardhat migration
  deploy/001_deploy_hub.ts
  deploy/008_deploy_log2pldsf.ts
  deploy/013_deploy_profile_storage.ts
  deploy/014_deploy_service_agreement_storage_v1.ts
  deploy/021_deploy_service_agreement_v1.ts
  test/assertionStorage.test.ts
  test/contentAsset.test.ts
  test/helpers/constants.ts
  test/hub.test.ts
  test/identity.test.ts
  test/identityStorage.test.ts
  test/parametersStorage.test.ts
  test/profile.test.ts
  test/profileStorage.test.ts
  test/serviceAgreementStorageV1.test.ts
  test/serviceAgreementV1.test.ts
  test/shardingTableStorage.test.ts
  test/staking.test.ts
  test/whitelistStorage.test.ts
  utils/helpers.ts
Labels: v6, internal process, tests
