Repository OriginTrail/dkg-evm-module, pull requests merged in 2024-02, with the labels that each got.

#218 Fixed CommitManagerV1/V1U1 bugs, fixed LinearSum score calculation to avoid underflows, added tests for CommitManagerV1 and LinearSum
  abi/CommitManagerV2.json
  abi/CommitManagerV2U1.json
  abi/ShardingTableStorageV2.json
  contracts/v2/CommitManagerV1.sol
  contracts/v2/CommitManagerV1U1.sol
  contracts/v2/ShardingTable.sol
  contracts/v2/errors/CommitManagerErrorsV2.sol
  contracts/v2/scoring/LinearSum.sol
  contracts/v2/storage/ShardingTableStorage.sol
  contracts/v2/structs/ShardingTableStructsV2.sol
  hardhat.node.config.ts
  test/v2/unit/CommitManagerV2.test.ts
  test/v2/unit/LinearSum.test.ts
Labels: bug, tests

#220 Added Stake balancing for score calculations, added possibility to on…
  abi/NodeOperatorFeeChangesStorage.json
  contracts/v1/Profile.sol
  contracts/v1/scoring/log2pldsf.sol
  contracts/v1/storage/ParametersStorage.sol
  contracts/v2/Staking.sol
  contracts/v2/scoring/LinearSum.sol
  contracts/v2/storage/NodeOperatorFeeChangesStorage.sol
  test/v1/unit/ParametersStorage.test.ts
  test/v1/unit/Profile.test.ts
Labels: feature, improvement

#221 Scale down score to uint40
  contracts/v2/scoring/LinearSum.sol
  contracts/v2/utils/ScaleDownLibrary.sol
  test/v2/unit/CommitManagerV2.test.ts
  test/v2/unit/LinearSum.test.ts
Labels: bug

#225 Fixed bug in Identity contract, added possibility to register multiple op wallets on profile creation using ProfileV2, added unit tests
  abi/Identity.json
  abi/ParametersStorage.json
  abi/ProfileV2.json
  contracts/v1/Identity.sol
  contracts/v1/storage/ParametersStorage.sol
  contracts/v2/CommitManagerV1.sol
  contracts/v2/Profile.sol
  contracts/v2/constants/HashRingConstants.sol
  contracts/v2/errors/ProfileErrors.sol
  contracts/v2/scoring/LinearSum.sol
  contracts/v2/storage/NodeOperatorFeeChangesStorage.sol
  test/v1/unit/Identity.test.ts
  test/v2/unit/ProfileV2.test.ts
Labels: bug, feature, v6

#226 Removed ProfileV2 in favour of Profile update
  abi/Profile.json
  abi/ProfileV2.json
  contracts/v1/Profile.sol
  contracts/v1/errors/ProfileErrors.sol
  contracts/v1/errors/StakingErrors.sol
  contracts/v2/Profile.sol
  contracts/v2/Staking.sol
  deploy/031_deploy_profile.ts
  deploy/031_deploy_profile_v2.ts
  deploy/032_deploy_commit_manager_v2.ts
  deploy/033_deploy_commit_manager_v1.ts
  deploy/034_deploy_commit_manager_v2_u1.ts
  deploy/035_deploy_commit_manager_v1_u1.ts
  deploy/036_deploy_proof_manager_v1.ts
  deploy/037_deploy_proof_manager_v1_u1.ts
  deploy/038_deploy_service_agreement_v1.ts
  deploy/039_deploy_content_asset.ts
  index.ts
  test/v1/integration/ContentAsset.test.ts
  test/v1/unit/CommitManagerV1.test.ts
  test/v1/unit/CommitManagerV1U1.test.ts
  test/v1/unit/Profile.test.ts
  test/v1/unit/ProofManagerV1.test.ts
  test/v1/unit/ProofManagerV1U1.test.ts
  test/v1/unit/ShardingTableStorage.test.ts
  test/v1/unit/Staking.test.ts
  test/v2/unit/CommitManagerV2.test.ts
  test/v2/unit/CommitManagerV2U1.test.ts
  test/v2/unit/ProfileV2.test.ts
  test/v2/unit/ShardingTableV2.test.ts
  test/v2/unit/StakingV2.test.ts
Labels: improvement

#224 Added ProfileV2 with possibility to set initial operator fee on profile creation, added limit for the Sharding Table size
  abi/Identity.json
  abi/ParametersStorage.json
  abi/Profile.json
  abi/StakingV2.json
  contracts/v1/Identity.sol
  contracts/v1/Profile.sol
  contracts/v1/errors/GeneralErrors.sol
  contracts/v1/errors/ProfileErrors.sol
  contracts/v1/errors/StakingErrors.sol
  contracts/v1/storage/ParametersStorage.sol
  contracts/v2/CommitManagerV1.sol
  contracts/v2/Staking.sol
  contracts/v2/constants/HashRingConstants.sol
  contracts/v2/errors/ProfileErrors.sol
  contracts/v2/errors/ShardingTableErrors.sol
  contracts/v2/scoring/LinearSum.sol
  contracts/v2/storage/NodeOperatorFeeChangesStorage.sol
  deployments/gnosis_chiado_dev_contracts.json
  deployments/gnosis_chiado_test_contracts.json
  deployments/parameters.json
  hardhat.node.config.ts
  index.ts
  package-lock.json
  package.json
  test/v1/integration/ContentAsset.test.ts
  test/v1/unit/CommitManagerV1.test.ts
  test/v1/unit/CommitManagerV1U1.test.ts
  test/v1/unit/Identity.test.ts
  test/v1/unit/Profile.test.ts
  test/v1/unit/ProofManagerV1.test.ts
  test/v1/unit/ProofManagerV1U1.test.ts
  test/v1/unit/ShardingTableStorage.test.ts
  test/v1/unit/Staking.test.ts
  test/v2/unit/CommitManagerV2.test.ts
  test/v2/unit/CommitManagerV2U1.test.ts
  test/v2/unit/ShardingTableV2.test.ts
  test/v2/unit/StakingV2.test.ts
Labels: bug, v6, improvement

#229 Fixed bug in _addStake function, added identityId to SharesMinted/Burned events
  abi/StakingV2.json
  contracts/v2/Staking.sol
  package-lock.json
  package.json
Labels: bug, v6, release, improvement

#232 Gnosis Testnet & NeuroWeb Testnet contracts redeployed
  deployments/gnosis_chiado_test_contracts.json
  deployments/otp_testnet_contracts.json
Labels: chore

#237 Added reward to the ProofSubmitted events
  abi/ProofManagerV1.json
  abi/ProofManagerV1U1.json
  abi/StakingV2.json
  contracts/v1/ProofManagerV1.sol
  contracts/v1/ProofManagerV1U1.sol
  contracts/v2/Staking.sol
  test/v1/unit/ProofManagerV1.test.ts
  test/v1/unit/ProofManagerV1U1.test.ts
Labels: v6, improvement

#239 Fixed unchecked initial operator fee in the Profile, redeployed contr…
  abi/Profile.json
  contracts/v1/Profile.sol
  contracts/v1/errors/ProfileErrors.sol
  deploy/001_deploy_hub_v2.ts
  deploy/002_deploy_hub.ts
  deployments/gnosis_mainnet_contracts.json
  deployments/otp_mainnet_contracts.json
  test/v1/unit/Profile.test.ts
  utils/helpers.ts
Labels: bug, v6, improvement
